steps:
  # Install node packages
  - name: 'gcr.io/static-retina-404402/pnpm:node-20.9.0'
    entrypoint: 'pnpm'
    args: ['install']

  # Build productive files
  - name: 'gcr.io/static-retina-404402/pnpm:node-20.9.0'
    entrypoint: 'pnpm'
    args: ['nx', 'run', 'myorg:build:development']

  # Deploy to google cloud app engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=${_PR_NUMBER}', '--no-promote']
