steps:

  # Node.js バージョン 16.14.0 のイメージをプルする
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - 'node:16.14.0'

  # Install node packages
  - name: 'gcr.io/cloud-builders/yarn'
    args: [ 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/yarn'
    args: [ 'run', 'build', '--prod' ]

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']
