steps:
  # Restore Cache
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'restore-node-modules'
    args: ['cp', 'gs://my-org_node_modules/node_modules.tar.gz', '/workspace/']

  - name: 'ubuntu'
    id: 'uncompress-node-modules'
    entrypoint: '/bin/bash'
    args:
      [
        '-c',
        'if [ -f /workspace/node_modules.tar.gz ]; then tar -xzf /workspace/node_modules.tar.gz -C /workspace && rm /workspace/node_modules.tar.gz; fi',
      ]

  # Install node packages
  - name: 'gcr.io/static-retina-404402/pnpm:node-20.9.0'
    id: 'install-node-packages'
    entrypoint: 'pnpm'
    args: ['install']

  # Build Myorg
  - name: 'gcr.io/static-retina-404402/pnpm:node-20.9.0'
    id: 'build-myorg'
    entrypoint: 'pnpm'
    args: ['nx', 'run', 'myorg:build:development']

  # Deploy to google cloud app engine
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-app'
    args: ['app', 'deploy', '--version=${_PR_NUMBER}', '--no-promote']

  # Delete old deploy versions
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'delete-old-versions'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" |
        grep -v '^prod$' | tail -n +6 | xargs -r gcloud app versions delete --quiet

  # Calculate pnpm-lock.yaml hash test
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'calculate-pnpm-lock-hash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        md5sum /workspace/pnpm-lock.yaml > /workspace/current_pnpm_lock_hash.txt
        gsutil cp gs://my-org_node_modules/last_pnpm_lock_hash.txt /workspace/last_pnpm_lock_hash.txt

  # Save Cache
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'save-node-modules'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if cmp -s /workspace/current_pnpm_lock_hash.txt /workspace/last_pnpm_lock_hash.txt; then
          echo "pnpm-lock.yaml unchanged, skipping cache save."
        else
          tar -czf /workspace/node_modules.tar.gz -C /workspace node_modules
          gsutil cp /workspace/node_modules.tar.gz gs://my-org_node_modules/node_modules.tar.gz
          gsutil cp /workspace/current_pnpm_lock_hash.txt gs://my-org_node_modules/last_pnpm_lock_hash.txt

        fi
