steps:
  # Restore Cache
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://my-org_node_modules/node_modules.tar.gz', '/workspace/']

  - name: 'ubuntu'
    entrypoint: '/bin/bash'
    args:
      [
        '-c',
        'if [ -f /workspace/node_modules.tar.gz ]; then tar -xzf /workspace/node_modules.tar.gz -C /workspace && rm /workspace/node_modules.tar.gz; fi',
      ]

  # Install node packages
  - name: 'gcr.io/static-retina-404402/pnpm:node-20.9.0'
    entrypoint: 'pnpm'
    args: ['install']

  # Build productive files
  - name: 'gcr.io/static-retina-404402/pnpm:node-20.9.0'
    entrypoint: 'pnpm'
    args: ['nx', 'run', 'myorg:build:development']

  # test
  # - name: 'ubuntu'
  #   entrypoint: '/bin/bash'
  #   args: ['-c', 'rm -rf /workspace/workspace']

  # Deploy to google cloud app engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=${_PR_NUMBER}', '--no-promote']

  # Save Cache
  - name: 'ubuntu'
    entrypoint: '/bin/bash'
    args:
      [
        '-c',
        'tar -czf /workspace/node_modules.tar.gz -C /workspace node_modules',
      ]

  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      [
        'cp',
        '/workspace/node_modules.tar.gz',
        'gs://my-org_node_modules/node_modules.tar.gz',
      ]
