name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t my-org-image .
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          region: asia-northeast1
          image: my-org-image
